import './globals.css'
import { Inter } from 'next/font/google';
import Header from './components/header/header';
const inter = Inter({ subsets: ['latin'] });
import AuthProvider from './components/authProvider/authProvider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <Header/>   
        {children}
      </AuthProvider>
      </body>
    </html>
  )
}